kind: pipeline
type: docker
name: tails

steps:
  - name: build
    image: gradle:jdk17
    commands:
      - gradle bootJar -x test

  - name: push-alnitak
    image: plugins/docker
    depends_on: [build]
    settings:
      registry: registry.furryverse.moe
      repo: registry.furryverse.moe/furryverse/alnitak
      dockerfile: alnitak/Dockerfile
      use_cache: true
      username: furryverse
      password:
        from_secret: REGISTRY_PASSWORD
      auto_tag: true
