kind: pipeline
type: docker
name: tails

clone:
  disable: true

steps:
  - name: clone
    image: alpine/git
    environment:
      GIT_SSL_VERIFY:
        from_secret: git_ssl_verify
      GIT_REPO:
        from_secret: git_repo
    commands:
      - git config --global http.sslVerify $GIT_SSL_VERIFY
      - git clone $GIT_REPO .

  - name: build
    image: gradle:jdk17
    commands:
      - gradle bootJar -x test