package moe.furryverse.server.common.security;

public enum Access {
    // Cluster
    CLUSTER_LIST, CLUSTER_GET, CLUSTER_CREATE, CLUSTER_UPDATE, CLUSTER_DELETE,

    // Galaxy
    GALAXY_LIST, GALAXY_GET, GALAXY_CREATE, GALAXY_UPDATE, GALAXY_DELETE,

    // Nucleus
    NUCLEUS_LIST, NUCLEUS_GET, NUCLEUS_CREATE, NUCLEUS_UPDATE, NUCLEUS_DELETE,

    // Asteroid
    ASTEROID_LIST, ASTEROID_GET, ASTEROID_CREATE, ASTEROID_UPDATE, ASTEROID_DELETE,

    // Comet
    COMET_LIST, COMET_GET, COMET_CREATE, COMET_UPDATE, COMET_DELETE,

    // Planet
    PLANET_LIST, PLANET_GET, PLANET_CREATE, PLANET_UPDATE, PLANET_DELETE,

    // Stardust
    STARDUST_LIST, STARDUST_GET, STARDUST_CREATE, STARDUST_UPDATE, STARDUST_DELETE,

    // 文件接口
    FILE_LIST, FILE_GET, FILE_UPLOAD, FILE_DELETE
}
