# server
server.port: 10002

# spring
spring.application.name: ascella

# rpc
dubbo.application.name: ${spring.application.name}
dubbo.protocol.name: dubbo
dubbo.protocol.port: -1
dubbo.registry.client: curator
dubbo.registry.username: ${ZOOKEEPER_USERNAME}
dubbo.registry.password: ${ZOOKEEPER_PASSWORD}
dubbo.registry.address: zookeeper://${ZOOKEEPER_HOST}:${ZOOKEEPER_PORT}
dubbo.registry.use-as-config-center: false